In [34]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 500)
import matplotlib as mt
import matplotlib.pyplot as plt
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import sklearn
from sklearn import cluster
%matplotlib inline 
#makes matplotlib show up!

In [35]:
traffic = pd.read_csv('/Users/eric_ha/Desktop/Traffic Data/us-traffic-2015/dot_traffic_2015.txt.gz', compression='gzip',
                         header=0, sep=',', quotechar='"')

In [25]:
traffic.head(10)
#showing first 10 rows

,date,day_of_data,day_of_week,direction_of_travel,direction_of_travel_name,fips_state_code,functional_classification,functional_classification_name,lane_of_travel,month_of_data,...,traffic_volume_counted_after_1500_to_1600,traffic_volume_counted_after_1600_to_1700,traffic_volume_counted_after_1700_to_1800,traffic_volume_counted_after_1800_to_1900,traffic_volume_counted_after_1900_to_2000,traffic_volume_counted_after_2000_to_2100,traffic_volume_counted_after_2100_to_2200,traffic_volume_counted_after_2200_to_2300,traffic_volume_counted_after_2300_to_2400,year_of_data
0,2015-04-07,7,3,1,North,56,3R,Rural: Principal Arterial - Other,1,4,...,89,122,124,110,69,73,28,12,6,15
1,2015-09-26,26,7,7,West,21,1U,Urban: Principal Arterial - Interstate,2,9,...,1617,1669,1308,1068,928,885,798,650,613,15
2,2015-06-16,16,3,3,East,6,1U,Urban: Principal Arterial - Interstate,0,6,...,4244,4405,4609,4361,3272,2243,2050,1453,892,15
3,2015-04-26,26,1,5,South,55,1U,Urban: Principal Arterial - Interstate,1,4,...,1011,959,851,708,559,457,297,207,110,15
4,2015-05-23,23,7,3,East,4,4R,Rural: Minor Arterial,0,5,...,83,61,55,35,29,21,23,9,7,15
5,2015-07-25,25,7,5,South,44,2U,Urban: Principal Arterial - Other Freeways or ...,0,7,...,2673,2746,2564,2257,2140,2060,2156,1873,1590,15
6,2015-09-10,10,5,3,East,19,3U,Urban: Principal Arterial - Other,2,9,...,542,571,559,395,351,262,217,153,61,15
7,2015-10-27,27,3,3,East,36,4U,Urban: Minor Arterial,1,10,...,238,278,250,154,130,84,56,21,14,15
8,2015-06-26,26,6,7,West,42,1R,Rural: Principal Arterial - Interstate,2,6,...,740,784,822,703,425,192,159,150,168,15
9,2015-05-12,12,3,5,South,40,2U,Urban: Principal Arterial - Other Freeways or ...,2,5,...,1662,1673,1519,1148,914,808,555,468,270,15

In [31]:
traffic.shape

(7140391, 36)

In [44]:
traffic_clean = traffic.drop(['direction_of_travel','fips_state_code', 'lane_of_travel', 'year_of_data'], axis=1)

In [45]:
traffic_clean.head(10)

,date,day_of_data,day_of_week,direction_of_travel_name,functional_classification,functional_classification_name,month_of_data,record_type,restrictions,station_id,...,traffic_volume_counted_after_1400_to_1500,traffic_volume_counted_after_1500_to_1600,traffic_volume_counted_after_1600_to_1700,traffic_volume_counted_after_1700_to_1800,traffic_volume_counted_after_1800_to_1900,traffic_volume_counted_after_1900_to_2000,traffic_volume_counted_after_2000_to_2100,traffic_volume_counted_after_2100_to_2200,traffic_volume_counted_after_2200_to_2300,traffic_volume_counted_after_2300_to_2400
0,2015-04-07,7,3,North,3R,Rural: Principal Arterial - Other,4,3,NaN,000084,...,129,89,122,124,110,69,73,28,12,6
1,2015-09-26,26,7,West,1U,Urban: Principal Arterial - Interstate,9,3,NaN,056P94,...,1453,1617,1669,1308,1068,928,885,798,650,613
2,2015-06-16,16,3,East,1U,Urban: Principal Arterial - Interstate,6,3,NaN,077590,...,4077,4244,4405,4609,4361,3272,2243,2050,1453,892
3,2015-04-26,26,1,South,1U,Urban: Principal Arterial - Interstate,4,3,NaN,450001,...,1043,1011,959,851,708,559,457,297,207,110
4,2015-05-23,23,7,East,4R,Rural: Minor Arterial,5,3,NaN,102210,...,87,83,61,55,35,29,21,23,9,7
5,2015-07-25,25,7,South,2U,Urban: Principal Arterial - Other Freeways or ...,7,3,NaN,008148,...,2700,2673,2746,2564,2257,2140,2060,2156,1873,1590
6,2015-09-10,10,5,East,3U,Urban: Principal Arterial - Other,9,3,NaN,000823,...,539,542,571,559,395,351,262,217,153,61
7,2015-10-27,27,3,East,4U,Urban: Minor Arterial,10,3,NaN,009582,...,217,238,278,250,154,130,84,56,21,14
8,2015-06-26,26,6,West,1R,Rural: Principal Arterial - Interstate,6,3,NaN,000393,...,751,740,784,822,703,425,192,159,150,168
9,2015-05-12,12,3,South,2U,Urban: Principal Arterial - Other Freeways or ...,5,3,NaN,AVC068,...,1364,1662,1673,1519,1148,914,808,555,468,270